name: black-action

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  black_formatter:
    name: runner / black formatter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Black formatter
        uses: rickstaa/action-black@v1.3.3
        with:
          black_args: >
            . --check --diff --exclude '*generated_tests*'
